package com.example.vaadindocumentmanager;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.TextFileProperty;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class DocEditor extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private Panel formPanel;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private InlineDateField inlineDateField_1;
	@AutoGenerated
	private CheckBox sex;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private TextField name;
	@AutoGenerated
	private TextArea htmlEdit;
	@AutoGenerated
	private RichTextArea viewEdit;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DocEditor() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public void setPropertyDataSource(TextFileProperty doc) {
		htmlEdit.setPropertyDataSource(doc);
		viewEdit.setPropertyDataSource(doc);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1, "top:10.0px;left:10.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		
		// viewEdit
		viewEdit = new RichTextArea();
		viewEdit.setImmediate(false);
		viewEdit.setWidth("100.0%");
		viewEdit.setHeight("100.0%");
		tabSheet_1.addTab(viewEdit, "编辑器", null);
		
		// htmlEdit
		htmlEdit = new TextArea();
		htmlEdit.setImmediate(false);
		htmlEdit.setWidth("100.0%");
		htmlEdit.setHeight("100.0%");
		tabSheet_1.addTab(htmlEdit, "纯代码", null);
		
		// formPanel
		formPanel = buildFormPanel();
		tabSheet_1.addTab(formPanel, "表单", null);
		
		return tabSheet_1;
	}

	@AutoGenerated
	private Panel buildFormPanel() {
		// common part: create layout
		formPanel = new Panel();
		formPanel.setImmediate(false);
		formPanel.setWidth("100.0%");
		formPanel.setHeight("100.0%");
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		formPanel.setContent(verticalLayout_1);
		
		return formPanel;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("100.0%");
		verticalLayout_1.setHeight("100.0%");
		verticalLayout_1.setMargin(false);
		
		// name
		name = new TextField();
		name.setCaption("用户名");
		name.setImmediate(false);
		name.setWidth("-1px");
		name.setHeight("-1px");
		verticalLayout_1.addComponent(name);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("性别");
		verticalLayout_1.addComponent(label_1);
		
		// sex
		sex = new CheckBox();
		sex.setCaption("男");
		sex.setImmediate(false);
		sex.setWidth("-1px");
		sex.setHeight("-1px");
		verticalLayout_1.addComponent(sex);
		
		// inlineDateField_1
		inlineDateField_1 = new InlineDateField();
		inlineDateField_1.setCaption("日历");
		inlineDateField_1.setImmediate(false);
		inlineDateField_1.setWidth("-1px");
		inlineDateField_1.setHeight("-1px");
		verticalLayout_1.addComponent(inlineDateField_1);
		
		return verticalLayout_1;
	}

}
